"""Shared immutable vocabulary for the knowledge substrate.

The models here are the served wire vocabulary of the knowledge store: entity, operation,
refusal and snapshot shapes that cross the storage boundary. They hold no SQL, no Git
resolution and no authorization decision. A literal state or result code that decides
something lives here and is imported by the decider, never defined by it and imported back
down.
"""

from agents_remember.models.knowledge.authorship import (
    ACCEPTED_STATE,
    PROPOSED_STATE,
    Authorship,
    KnowledgeState,
)
from agents_remember.models.knowledge.context import (
    KNOWLEDGE_SCHEMA_NAME,
    AdmittedKnowledgeDestination,
    KnowledgeSchemaIdentity,
)
from agents_remember.models.knowledge.digest import (
    FAMILY_REVISION_PAYLOAD_VERSION,
    REVISION_PAYLOAD_VERSION,
    canonical_family_revision_payload,
    canonical_revision_payload,
    family_revision_payload_digest,
    revision_payload_digest,
    sealed_family_revision,
    sealed_revision,
)
from agents_remember.models.knowledge.family import (
    FamilyDraft,
    FamilyIdentity,
    FamilyRevision,
    FamilyRevisionDraft,
    StoredFamilyRevision,
)
from agents_remember.models.knowledge.graph import (
    UNCLASSIFIED_ROLE,
    AnchorRealizations,
    FamilyMember,
    FamilyMemberDraft,
    FamilyMembers,
    InvariantFamilies,
    RealizationClaim,
    RealizationClaimDraft,
    RealizationClaims,
    RealizationRole,
)
from agents_remember.models.knowledge.invariant import (
    InvariantDraft,
    InvariantIdentity,
    InvariantRevision,
    StoredInvariantRevision,
)
from agents_remember.models.knowledge.repository import RepositoryIdentity
from agents_remember.models.knowledge.result import (
    AnchorEndpoint,
    AnchorReference,
    CreateFamilyMemberResult,
    CreateFamilyResult,
    CreateFamilyRevisionResult,
    CreateInvariantResult,
    CreateRealizationClaimResult,
    CreateRevisionResult,
    CreateSourceAnchorResult,
    FamilyMemberRequest,
    FamilyRequest,
    FamilyRevisionRequest,
    InvariantRequest,
    KnowledgeOperation,
    KnowledgeRefusal,
    KnowledgeRefusalCode,
    NewAnchor,
    RealizationClaimRequest,
    RemoveFamilyMemberRequest,
    RemoveFamilyMemberResult,
    RemoveRealizationClaimRequest,
    RemoveRealizationClaimResult,
    RemoveSourceAnchorRequest,
    RemoveSourceAnchorResult,
    RepositoryCreationResult,
    RevisionDraft,
    RevisionRequest,
    SourceAnchorRequest,
)
from agents_remember.models.knowledge.source import (
    FileLocator,
    GitBlobIdentity,
    LineRangeLocator,
    SourceAnchor,
    SourceAnchorDraft,
    SourceIdentity,
    SourceLocator,
    SymbolLocator,
)

__all__ = [
    "ACCEPTED_STATE",
    "FAMILY_REVISION_PAYLOAD_VERSION",
    "KNOWLEDGE_SCHEMA_NAME",
    "PROPOSED_STATE",
    "REVISION_PAYLOAD_VERSION",
    "UNCLASSIFIED_ROLE",
    "AdmittedKnowledgeDestination",
    "AnchorEndpoint",
    "AnchorRealizations",
    "AnchorReference",
    "Authorship",
    "CreateFamilyMemberResult",
    "CreateFamilyResult",
    "CreateFamilyRevisionResult",
    "CreateInvariantResult",
    "CreateRealizationClaimResult",
    "CreateRevisionResult",
    "CreateSourceAnchorResult",
    "FamilyDraft",
    "FamilyIdentity",
    "FamilyMember",
    "FamilyMemberDraft",
    "FamilyMemberRequest",
    "FamilyMembers",
    "FamilyRequest",
    "FamilyRevision",
    "FamilyRevisionDraft",
    "FamilyRevisionRequest",
    "FileLocator",
    "GitBlobIdentity",
    "InvariantDraft",
    "InvariantFamilies",
    "InvariantIdentity",
    "InvariantRequest",
    "InvariantRevision",
    "KnowledgeOperation",
    "KnowledgeRefusal",
    "KnowledgeRefusalCode",
    "KnowledgeSchemaIdentity",
    "KnowledgeState",
    "LineRangeLocator",
    "NewAnchor",
    "RealizationClaim",
    "RealizationClaimDraft",
    "RealizationClaimRequest",
    "RealizationClaims",
    "RealizationRole",
    "RemoveFamilyMemberRequest",
    "RemoveFamilyMemberResult",
    "RemoveRealizationClaimRequest",
    "RemoveRealizationClaimResult",
    "RemoveSourceAnchorRequest",
    "RemoveSourceAnchorResult",
    "RepositoryCreationResult",
    "RepositoryIdentity",
    "RevisionDraft",
    "RevisionRequest",
    "SourceAnchor",
    "SourceAnchorDraft",
    "SourceAnchorRequest",
    "SourceIdentity",
    "SourceLocator",
    "StoredFamilyRevision",
    "StoredInvariantRevision",
    "SymbolLocator",
    "canonical_family_revision_payload",
    "canonical_revision_payload",
    "family_revision_payload_digest",
    "revision_payload_digest",
    "sealed_family_revision",
    "sealed_revision",
]
