"""JSON-primary task documents (``ar-task-document/v1``) and their markdown render.

The JSON document is the source of truth; ``task.md`` is a deterministic render
of it. This package owns the schema (``document``), the renderer (``render``),
and the read/write store (``store``); the ``task_doc`` MCP tool authors them and
the observer projects them (keyed by lifecycle).
"""

from __future__ import annotations

from .document import (
    TASK_DOCUMENT_SCHEMA,
    CodeExample,
    Decision,
    DocKind,
    DocStatus,
    HeaderNote,
    LeafPlacement,
    MasterExecutionNature,
    RouteReviewRecord,
    RouteReviewUnit,
    RouteReviewVerdict,
    Section,
    SprintExecutionEdge,
    SprintExecutionEndpoint,
    SprintExecutionGraph,
    SprintExecutionNode,
    SprintSeat,
    SprintSeatState,
    Step,
    StepDisposition,
    StepStatus,
    SubStep,
    SubTaskRef,
    TaskDocument,
    TaskEnclosureRef,
    current_step,
    derived_leaf_placement,
    leaf_placement_facts,
    numbering_drift_hints,
    resolve_graph_endpoint,
    series_done,
    series_total,
    step_done,
    step_total,
)
from .execution_graph_titles import (
    SprintGraphTitles,
    build_graph_titles,
    read_graph_titles,
)
from .readiness import CompletionBlocker, completion_blockers
from .render import render_markdown
from .store import (
    doc_stem,
    json_path_for,
    markdown_path_for,
    read_task_doc,
    write_task_doc,
    write_task_doc_batch,
    write_task_docs,
)

__all__ = [
    "TASK_DOCUMENT_SCHEMA",
    "CodeExample",
    "CompletionBlocker",
    "Decision",
    "DocKind",
    "DocStatus",
    "HeaderNote",
    "LeafPlacement",
    "MasterExecutionNature",
    "RouteReviewRecord",
    "RouteReviewUnit",
    "RouteReviewVerdict",
    "Section",
    "SprintExecutionEdge",
    "SprintExecutionEndpoint",
    "SprintExecutionGraph",
    "SprintExecutionNode",
    "SprintGraphTitles",
    "SprintSeat",
    "SprintSeatState",
    "Step",
    "StepDisposition",
    "StepStatus",
    "SubStep",
    "SubTaskRef",
    "TaskDocument",
    "TaskEnclosureRef",
    "build_graph_titles",
    "completion_blockers",
    "current_step",
    "derived_leaf_placement",
    "doc_stem",
    "json_path_for",
    "leaf_placement_facts",
    "markdown_path_for",
    "numbering_drift_hints",
    "read_graph_titles",
    "read_task_doc",
    "render_markdown",
    "resolve_graph_endpoint",
    "series_done",
    "series_total",
    "step_done",
    "step_total",
    "write_task_doc",
    "write_task_doc_batch",
    "write_task_docs",
]
